name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3 for Node.js 16/20 support
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Update to v4 for Node.js 16/20 support
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
